<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<UseSharedCompilation>false</UseSharedCompilation>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<COMPlus_EnableWriteXorExecute>0</COMPlus_EnableWriteXorExecute>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Api\" />
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dal\Dal.csproj" />
  </ItemGroup>

</Project>
